dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
install: true
script:
- "./gradlew build"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: V/2+FHcUSm76YtFHlxtElO/8qY12OWLQktsNWyv28zAwuMreLgp0OUO5h1ogFBeqJZMnNbrqw8CROJEGsJDstzAa4CoR92TrmCatvCTMGzIJ3BDfPjY/Ip2PisENCSUmnrdQbG7KGQG0vDu8NgllDnk17aVgpziTEjMv1qtzvO7Sdu1EGwMyD9ifZR13Rx/LnR967ualupMHujCbc34gwop7NNot/A6gWG9kLIJqgAeI9AYfFxmnl5GyJfV15wDBXJ/Y767736mWK2o8Av9TipRjsdvcNM80KQe7De/IJu3jJGejrevBa4tPfJM1Zz21yICeNj+2XOJ/WUb+zvWT+UV16U+8ENe2SFvY7P1LyKDekgwz2MQwS66qkx3/8V16Oh16WP4mhQnJeVJrkeDPwk5iADYjpuDXVlf8NK4Ufu7DNBOfLUzv5fw/dvQxSdlS2E5OcRZc9fAKf4uoBjLZOsTb/+F4QROFFk1jO5Qiseyj6zC119t8y9m2DYkK+so9JxLpdQIz32ODkFUKEvrp8NpXL80z8wl3QuH429mQd11dB7TuwJUIfIyW1SNH7Tk6W8IHw/9dqow+Ap2tD4WFJuy4dUpzRhgHuJfBr51k+0nPlTHsoiGk9FnsnGq49WeyrCFKHRrlN5I+/8TXuSrVhmz8O4sXDR+nyTiEbP7XOMA=
  - secure: AE0CzxNohZTXroTNyQrNH3l8swmvnBL5I/XpfRNwG+TCYXMWswad0yPJ9+k+0vhRs9tIcfmAs01GkIGK+rZPM/qXVAwy0DzKqJVptqaURqgwH6IonCZLKxYymw8Tk17NmzLOdOvbeD9gc9h4H3VET4r4RjeD7/QKDfAWnlUbd7l322d/B5n/KWlNrfMxNm/YNqhkWSouxGb86nWnZb6ByXq+1x8UYj7FW5SecvE4EC+sLSbl75hFuhZn6hruawNG1aEfmYCqy5fpL7flDPmPUhZ+pO92VK1MavcIENsvmC2wDWP46E3V6u4/+kQenXDf+YxymbZTYEsVkXyvkG88WzhOwnNGgCSy76/n4HuOg/3dyR+vkRM6BSpekbO0/IU+KWt7VKBv4HUv/axyvksR7hxeFyCwKEpHcSNN6HADlE1e0MVi3Io2gtJVKqqNWpgr7VdsbgnyP7gjCz9oaawNEyXgkA6iXcO5Qc5fbCiBtKyo8CDVK6nDXiWoY+Rcov9l603NBzdFHIkKjetkZuN1NuHaeiqqrnGksf3DPu5ESvBiuNLuabaZE83dSIdNhw3fh3u9T997nVp923g9LRujVTsSql2KnbsGmKm7XVSwKeNnNNc2UR7ue/0ZOpMQggAv/F/tQigzffZWWj30QNr85wsbEISJIQIKQL1Np51u6gs=
