name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: spotless check + build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: spotless check
      run: ./gradlew spotlessCheck

    - name: build project
      run: ./gradlew build
