name: prepare release

on: 
  release:
    types: [created]

jobs:
  deploy:
    name: prepare jar & update jitpack.io
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: build
        run: ./gradlew build -Pversion=${{ github.event.release.tag_name }}

      - name: upload assets to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./build/libs/*.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update JitPack
        uses: badasintended/autojitpack@v1
        with:
          version: ${{ github.event.release.tag_name }}
