name: prepare release

on: 
  release:
    types: [created]

jobs:
  upload-artifact:
    name: upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: build
        run: ./gradlew build -Pversion=${{ github.event.release.tag_name }}

      - name: upload assets to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./build/libs/*.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  update-jitpack:
    name: update jitpack releases
    runs-on: ubuntu-latest
    steps:
      - name: Update JitPack
        uses: badasintended/autojitpack@v1
        with:
          version: ${{ github.event.release.tag_name }}

  upload-package:
    name: upload github package registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: publish to gpr
        run: ./gradlew publishMavenPublicationToGprRepository -Pversion=${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
